name: Hexo CICD

on:
  push:
      branches:
      - hexo
      paths:
      - 'source/**'
      - 'themes/**'
      - '_config.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo
          submodules: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{runner.OS}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
          if_keep_commit_history: true
