name: Deploy Hexo site to Pages

on:
  workflow_dispatch:
  pull_request:
      branches:
      - $default-branch
      paths:
      - 'source/**'
      - 'themes/**'
      - '_config.yml'
      - '_config.next.yml'
      - 'package.json'
  push:
      branches:
      - $default-branch
      paths:
      - 'source/**'
      - 'themes/**'
      - '_config.yml'
      - '_config.next.yml'
      - 'package.json'

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 仅允许一项并发部署，跳过正在进行和最新排队之间的已排队运行。
# 但是，不要取消正在进行的运行，因为我们希望完成这些生产部署。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['16']
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: |
          npm install

      - name: Build with Hexo
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
