name: Hexo CICD

on:
  workflow_dispatch:
  pull_request:
      branches:
      - hexo
      paths:
      - 'source/**'
      - 'themes/**'
      - '_config.yml'
      - '_config.next.yml'
      - 'package.json'
  push:
      branches:
      - hexo
      paths:
      - 'source/**'
      - 'themes/**'
      - '_config.yml'
      - '_config.next.yml'
      - 'package.json'

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: hexo
          submodules: true

      - name: Checkout `gh-pages` Branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: public

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Get Time
        id: time
        run: |
          echo "time=$(TZ=UTC+8 date +'%Y-%m-%d %T GMT%:z')" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "GitHub CI Auto Builder at ${{ steps.time.outputs.time }}"

      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
