name: 'KeepActionAlive'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
      
      - name: 'Avoid Github Workflow being suspended'
        run: echo $(cat /proc/sys/kernel/random/uuid) > KeepAlive.txt
      
      - name: 'Commit Files'
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am '「GitHub Action」保活成功！'
          echo "status=success" >> $GITHUB_OUTPUT
           
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
