name: Scheduled dependencies update
on:
  schedule:
    - cron:  '0 0 * * 3'
    
jobs:
  update-deps:
    name: Update Node dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: 7850715+maboloshi@users.noreply.github.com
        AUTHOR_NAME: maboloshi
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
